### ISSUE TITLE
Still an active project?

### ISSUE THREAD

**Issue by petterreinholdtsen** [azukiapp/libnss-resolver#9]
Hi

I am considering if I should upload this package to Debian, but wonder if it is still an active project or not?

**Comment by fearenales** [comment]
Hi @petterreinholdtsen !
Yes, It is. And any contribution will be appreciated.

I've just checked your issues and PR. Be sure I'll keep you in touch.

`libnss-resolver` is used by [azk](https://github.com/azukiapp/azk) on Linux, and it has packages to Ubuntu, Fedora and Arch Linux. Certainly it would be great to have it to one more Linux distribution.

**Comment by petterreinholdtsen** [comment]
Glad to hear.  I hope the activity in the project causes my pull request and issues to get a quick response. :)
